"""Add coordinator_id to elections

Revision ID: 45189b02bf28
Revises: 16c238c972ad
Create Date: 2025-08-26 15:53:45.861590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45189b02bf28'
down_revision = '16c238c972ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['coordinator_id'], ['id'])

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('voter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('voter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('coordinator_id')

    # ### end Alembic commands ###
